Add components for power and ground
ra4king/CircuitSim pull request #75
Opened 2022-09-06 01:19 UTC by ausbin

Using constants has always bothered me a little bit for building circuits with transistors because it feels wrong, so add components for the power and ground symbols in Patt & Patel. They look like this:

![image](https://user-images.githubusercontent.com/431756/188526788-5382994b-ba8a-4a29-9926-06d8e9e78941.png)

The same circuit looks like this in Patt & Patel 3rd ed:

![image](https://user-images.githubusercontent.com/431756/188527119-e2a579e0-ca85-4cf5-968e-9665e08c6412.png)

I need to check with @pulkitgupta1217, @tmconte, and @sameer-s (and of course Mr. @ra4king) for thoughts on this. This is just my opinion and done for fun, curious what y'all think

2022-09-06 01:29 UTC, pulkitgupta1217 commented
I definitely agree there should be explicit elements for vdd and ground, whether they are unique components or just cosmetic changes to existing constants doesn't really matter to me. Only suggestion I have is to use the traditional circuit symbol for ground like the picture below

![Power-symbols](https://user-images.githubusercontent.com/21182764/188527904-916f5ae0-f25a-4d88-83d8-984227bf9c04.png)

2022-09-06 01:32 UTC, sameer-s commented
I feel that in 2110 a lot of students are more comfortable / used to thinking in 1s and 0s rather than in more electronics terms so I'm not sure how many of them would actually use these components. However, it could still be helpful at least because a lot of students get really confused with constant pins vs. input pins and so it might be nice to have a more visually distinct option for examples and such when appropriate.

That being said, I definitely think they should be new components if added, mostly because it would be very confusing to (for example) have a "ground" component connected as the carry-in for an adder, although it would be technically correct.

2022-09-06 20:06 UTC, ausbin commented
> I definitely agree there should be explicit elements for vdd and ground, whether they are unique components or just cosmetic changes to existing constants doesn't really matter to me. Only suggestion I have is to use the traditional circuit symbol for ground like the picture below
> 
> ![Power-symbols](https://user-images.githubusercontent.com/21182764/188527904-916f5ae0-f25a-4d88-83d8-984227bf9c04.png)

For what it's worth, I sent the following picture to Dr. Conte and asked which he liked best:

![three-transistors-walk-into-a-bar](https://user-images.githubusercontent.com/431756/188727844-37341f76-01e8-4ae8-aba2-03fd022d2c20.png)

along with the corresponding textbook diagram:

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/431756/188728237-9a092612-e718-4608-8032-2f0db33a3384.png)

He replied:
> I draw it like the textbook and like that way better than the 1, 0 thing on the left

I emailed Caleb but he hasn't replied yet, understandably

2022-09-08 05:32 UTC, ra4king requested changes

2022-09-08 05:32 UTC, ra4king commented on src/main/java/com/ra4king/circuitsim/gui/peers/wiring/PowerPeer.java
> +		setWidth(2);
You can set the width and the height in the super() call.

2022-09-08 05:32 UTC, ra4king commented on src/main/java/com/ra4king/circuitsim/gui/peers/wiring/GroundPeer.java
> +		setWidth(2);
You can set the width and the height in the super() call.

2022-09-08 05:32 UTC, ra4king commented on src/main/java/com/ra4king/circuitsim/gui/peers/wiring/GroundPeer.java
> +		                     new Image(ConstantPeer.class.getResourceAsStream("/images/Ground.png")),
Use GroundPeer here

2022-09-08 05:32 UTC, ra4king commented on src/main/java/com/ra4king/circuitsim/gui/peers/wiring/PowerPeer.java
> +		                     new Image(ConstantPeer.class.getResourceAsStream("/images/Power.png")),
Use PowerPeer here

2022-09-08 16:28 UTC, ausbin commented
Thanks for those catches, is this better?

2022-09-09 01:05 UTC, ra4king commented
I'm not a huge fan of the "T" and triangle shape but if this is what Conte wants...

2022-09-09 01:06 UTC, ra4king approved these changes

2022-09-09 01:06 UTC, merged

2022-09-09 01:41 UTC, ausbin commented
> I'm not a huge fan of the "T" and triangle shape but if this is what Conte wants...

@ra4king I don't think you have the same obligation to obey Patt & Patel that he does, if that makes sense. In my opinion, the appearance of the component could differ between vanilla CircuitSim and 2110 CircuitSim, even if the size & port locations don't. (If we want to go that route, I can make the PRs in the right places to avoid tormenting the TAs)

For ground, do you like this symbol more? (I have that written up already)

![image](https://user-images.githubusercontent.com/431756/189254215-97c00a68-742e-4b0d-a043-fbf9c53db4cd.png)

And for power, were you thinking something like this?

![image](https://user-images.githubusercontent.com/431756/189254359-21a7e741-ac17-404f-adf2-4e514fd9c16a.png)

This would match what Logisim does: http://www.cburch.com/logisim/docs/2.7/en/html/libs/wiring/const01.html

2022-09-10 02:14 UTC, ra4king commented
No it's ok, I googled a bit on this subject and the current ground symbol is fine. Let's add "VDD" to the power symbol?