Allow users to toggle the grid background
ra4king/CircuitSim pull request #82
Opened 2023-01-04 06:45 UTC by ausbin

Apparently Prof. Conte "wants gridless CircuitSim himself," so I'm hoping to upstream that to avoid emailing jars around. I didn't ask exactly why he wanted it, but I think this checkbox is useful when combined with 6d58b4218027f806a9.

Here it is in action (I wasn't sure where to put it, so I made a new "View" menu):

![image](https://user-images.githubusercontent.com/431756/210498580-f93d7804-2fb5-4cc6-a898-0ceda3cc8133.png)

![image](https://user-images.githubusercontent.com/431756/210498593-e257e444-1cb2-40b0-b92e-3cc7216c6bd8.png)

To the exporting point, the respective exported images look like:

![grid](https://user-images.githubusercontent.com/431756/210498658-f6182262-298c-4d95-9ec4-e6abc3a59c86.png)

versus

![no-grid](https://user-images.githubusercontent.com/431756/210498683-1e64399e-7489-4331-8b17-05c2751132cc.png)

I think the latter would be easier to read for students if you exported some work from lecture, for example. In particular, I find text easier to read in the latter. (Note that before exporting those images I toggled "view grid" manually, it's not automatic)

2023-01-04 06:50 UTC, ausbin commented
Ah, Jason (2110 head TA) said it's for exams

2023-01-05 06:24 UTC, ra4king requested changes

2023-01-05 06:24 UTC, ra4king commented on src/main/java/com/ra4king/circuitsim/gui/CircuitSim.java
> +		circuitManagers.values().stream().map(Pair::getValue).forEach(CircuitManager::paint);
Wrap this in the simulator.runSync call, so that its two callers don't have to.

2023-01-05 20:59 UTC, ra4king requested changes

2023-01-05 20:59 UTC, ra4king commented on src/main/java/com/ra4king/circuitsim/gui/CircuitManager.java
> +			if (drawGrid) {
Prefer a ternary within the setFill:

`graphics.drawFill(drawGrid ? Color.LIGHTGRAY : Color.WHITE)

2023-01-06 22:16 UTC, ra4king approved these changes

2023-01-06 22:16 UTC, merged